weapons_url_dict = {
    "WeapAK47_C" : "https://raw.githubusercontent.com/pubg/api-assets/master/assets/weapons/Item_Weapon_AK47.png",
    "WeapBerreta686_C" : "https://raw.githubusercontent.com/pubg/api-assets/master/assets/weapons/Item_Weapon_Berreta686.png",
    "WeapAUG_C" : "https://raw.githubusercontent.com/pubg/api-assets/master/assets/weapons/Item_Weapon_BigBomb.png",
    "WeapCowbar_C" : "https://raw.githubusercontent.com/pubg/api-assets/master/assets/weapons/Item_Weapon_Cowbar.png",
    "WeapCrossbow_1_C" : "https://raw.githubusercontent.com/pubg/api-assets/master/assets/weapons/Item_Weapon_Crossbow.png",
    "WeapDP-28_C" : "https://raw.githubusercontent.com/pubg/api-assets/master/assets/weapons/Item_Weapon_DP28.png",
    "ProjFlashBang_C" : "https://raw.githubusercontent.com/pubg/api-assets/master/assets/weapons/Item_Weapon_FlashBang.png",
    "WeapP18C_C" : "https://raw.githubusercontent.com/pubg/api-assets/master/assets/weapons/Item_Weapon_GLOCK18C.png",
    "WeapGroza_C" : "https://raw.githubusercontent.com/pubg/api-assets/master/assets/weapons/Item_Weapon_GROZA.png",
    "ProjGrenade_C" : "https://raw.githubusercontent.com/pubg/api-assets/master/assets/weapons/Item_Weapon_Grenade.png",
    "WeapHK416_C" : "https://raw.githubusercontent.com/pubg/api-assets/master/assets/weapons/Item_Weapon_HK416.png",
    "WeapKar98k_C" : "https://raw.githubusercontent.com/pubg/api-assets/master/assets/weapons/Item_Weapon_Kar98k.png",
    "WeapM16A4_C" : "https://raw.githubusercontent.com/pubg/api-assets/master/assets/weapons/Item_Weapon_M16A4.png",
    "WeapM1911_C" : "https://raw.githubusercontent.com/pubg/api-assets/master/assets/weapons/Item_Weapon_M1911.png",
    "WeapM24_C" : "https://raw.githubusercontent.com/pubg/api-assets/master/assets/weapons/Item_Weapon_M24.png",
    "WeapM249_C" : "https://raw.githubusercontent.com/pubg/api-assets/master/assets/weapons/Item_Weapon_M249.png",
    "WeapM9_C" : "https://raw.githubusercontent.com/pubg/api-assets/master/assets/weapons/Item_Weapon_M9.png",
    "WeapMk14_C" : "https://raw.githubusercontent.com/pubg/api-assets/master/assets/weapons/Item_Weapon_MI_Mk14EBR.png",
    "WeapMachete_C" : "https://raw.githubusercontent.com/pubg/api-assets/master/assets/weapons/Item_Weapon_Machete.png",
    "WeapMini14_C" : "https://raw.githubusercontent.com/pubg/api-assets/master/assets/weapons/Item_Weapon_Mini14.png",
    "ProjMolotov_C" : "https://raw.githubusercontent.com/pubg/api-assets/master/assets/weapons/Item_Weapon_Molotov.png",
    "WeapNagantM1895_C" : "https://raw.githubusercontent.com/pubg/api-assets/master/assets/weapons/Item_Weapon_NagantM1895.png",
    "WeapPan_C" : "https://raw.githubusercontent.com/pubg/api-assets/master/assets/weapons/Item_Weapon_Pan.png",
    "WeapSCAR-L_C" : "https://raw.githubusercontent.com/pubg/api-assets/master/assets/weapons/Item_Weapon_SCAR-L.png",
    "WeapSKS_C" : "https://raw.githubusercontent.com/pubg/api-assets/master/assets/weapons/Item_Weapon_SKS.png",
    "WeapSaiga12_C" : "https://raw.githubusercontent.com/pubg/api-assets/master/assets/weapons/Item_Weapon_Saiga12.png",
    "WeapSickle_C" : "https://raw.githubusercontent.com/pubg/api-assets/master/assets/weapons/Item_Weapon_Sickle.png",
    "ProjSmokeBomb_C" : "https://raw.githubusercontent.com/pubg/api-assets/master/assets/weapons/Item_Weapon_SmokeBomb.png",
    "WeapThompson_C" : "https://raw.githubusercontent.com/pubg/api-assets/master/assets/weapons/Item_Weapon_Thompson.png",
    "WeapUMP_C" : "https://raw.githubusercontent.com/pubg/api-assets/master/assets/weapons/Item_Weapon_UMP.png",
    "WeapUZI_C" : "https://raw.githubusercontent.com/pubg/api-assets/master/assets/weapons/Item_Weapon_UZI.png",
    "WeapVector_C" : "https://raw.githubusercontent.com/pubg/api-assets/master/assets/weapons/Item_Weapon_Vector.png",
    "WeapVSS_C" : "https://raw.githubusercontent.com/pubg/api-assets/master/assets/weapons/Item_Weapon_Vss_01.png",
    "WeapWinchester_C" : "https://raw.githubusercontent.com/pubg/api-assets/master/assets/weapons/Item_Weapon_Winchester.png",
    "WeapAWM_C" : "https://raw.githubusercontent.com/pubg/api-assets/master/assets/weapons/Item_Weapon_AWM.png",
    "Apple" : "https://raw.githubusercontent.com/pubg/api-assets/master/assets/weapons/Item_Weapon_Apple.png",
    "WeapSawnoff_C" : "https://raw.githubusercontent.com/pubg/api-assets/master/assets/weapons/Item_Weapon_Apple.png", # This currently has no image url
    "WeapWin94_C" : "https://raw.githubusercontent.com/pubg/api-assets/master/assets/weapons/Item_Weapon_Apple.png", # This currently has no image url
    "WeapWin1894_C" : "https://raw.githubusercontent.com/pubg/api-assets/master/assets/weapons/Item_Weapon_Apple.png", # This currently has no image url
}